An update on the new course wizard
DFE-Digital/bat-design-history pull request #113
Opened 2020-04-07 08:27 UTC by jesseyuen

This is a short entry to document the status of the new courses wizard, who currently has access and what the plans for full release are.

2020-04-21 08:06 UTC, fofr requested changes
This page needs to document the reasons we didn't roll out New course to everyone. Please also tell the story of this feature, as it's been a long time coming.

Please add screenshots of the new course wizard as it currently looks on live.

2020-04-21 14:12 UTC, jesseyuen commented
Good shout! I actually dont know much on the story of the feature beyond what is in the design history. Do you know if there was much scope change/updates during development? Please let me know :)

2020-04-23 10:54 UTC, jesseyuen commented
I've fleshed this one out, added some links to associated research, previous wizard entries and also added some dates for the beginning and ending of the build phase to help try and tell this chapter of the story.

As a bonus while writing this I found a bug in the live wizard and also tidied up some of our internal processes that Support use for providers still using the google form :)

2020-04-24 08:20 UTC, fofr requested changes
Nice. Just a few suggested tweaks to the content.

2020-04-24 08:20 UTC, fofr commented on app/posts/publish-teacher-training-courses/2020-02-15-new-course-wizard-available.md
> +title: The new course wizard is available for accredited bodies
```suggestion
title: New course wizard as launched for accredited bodies
```

2020-04-24 08:20 UTC, fofr commented on app/posts/publish-teacher-training-courses/2020-02-15-new-course-wizard-available.md
> +
```suggestion
## Why the wizard is not yet available to school directs

```

2020-04-24 08:20 UTC, fofr commented on app/posts/publish-teacher-training-courses/2020-02-15-new-course-wizard-available.md
> +School directs will not receive access to the new course wizard until Publish can automatically notify them that a course they accredited has been created.
```suggestion
School directs will not receive access to the new course wizard until Publish can automatically notify their accredited body that a course has been created. 
```

2020-04-24 08:20 UTC, fofr commented on app/posts/publish-teacher-training-courses/2020-02-15-new-course-wizard-available.md
> +An accredited body needs to be notified immediately when courses they accredit are created so they can maintain accurate data in their record systems. This was highlighted in [Accredited bodies resea
```suggestion
An accredited body needs to be notified immediately so they can maintain accurate data in their record systems. This was highlighted in [Accredited bodies research - Reporting round 2](publish-teacher-training-courses/accredited-bodies-research-round-2).
```

2020-04-24 08:20 UTC, fofr commented on app/posts/publish-teacher-training-courses/2020-02-15-new-course-wizard-available.md
> +After recieving the request, DfE support creates the course manually and notifies both the school direct and associated accredited body via email of the new course’s availability.
```suggestion
After receiving the request, DfE support creates the course manually and notifies both the school direct and associated accredited body via email of the new course’s availability.
```

2020-04-24 09:31 UTC, merged