Add post: How data flows through the service line
DFE-Digital/bat-design-history pull request #1211
Opened 2024-05-31 11:41 UTC by simonwhatley

2024-05-31 11:42 UTC, simonwhatley commented
![](https://github.trello.services/images/mini-trello-icon.png) [ITT Data Flow Diagram](https://trello.com/c/1Nro3cpo/7111-itt-data-flow-diagram)

2024-06-03 11:01 UTC, ralph-hawkins approved these changes
👍🏻 looks good — I've added couple of minor thoughts

2024-06-03 11:01 UTC, ralph-hawkins commented on app/posts/register-trainee-teachers/2024-05-28-how-data-flows-through-the-service-line.md
> +We mapped what data is created and consumed and how it flows through the ‘Becoming a teacher’ service line.
I think it might be useful to say something like – as of ‘June 2024’, so it’s clear that this is a snapshot it time.

2024-06-03 11:01 UTC, ralph-hawkins commented on app/posts/register-trainee-teachers/2024-05-28-how-data-flows-through-the-service-line.md
> +The service line includes several distinct data entities:
I'm not sure they are all that ‘distinct’? It might be more accurate to say something like – for the sake of this diagram we’ve identified these entities, however they are not treated as distinct by the services.

2024-06-03 14:09 UTC, andrewscrivener requested changes
Looks good to me apart from a couple of typos on the diagram.

2024-06-03 14:09 UTC, andrewscrivener commented on app/images/register-trainee-teachers/how-data-flows-through-the-service-line/itt-data-flow-diagram.png
I notice the following typos on the diagram;
* In the provider entity swim lane. Bullet point "updated night;y"
* Title in the left column - "Provider to school realtionship"

2024-06-03 14:48 UTC, simonwhatley commented on app/images/register-trainee-teachers/how-data-flows-through-the-service-line/itt-data-flow-diagram.png
We've updated the diagram, so typos should now be resolved.

2024-06-03 14:49 UTC, simonwhatley commented on app/posts/register-trainee-teachers/2024-05-28-how-data-flows-through-the-service-line.md
> +The service line includes several distinct data entities:
Okay, I've made a small change to remove 'distinct'.

2024-06-03 14:49 UTC, simonwhatley commented on app/posts/register-trainee-teachers/2024-05-28-how-data-flows-through-the-service-line.md
> +We mapped what data is created and consumed and how it flows through the ‘Becoming a teacher’ service line.
Yep, added a date to correspond to the one on the diagram.

2024-06-03 15:13 UTC, andrewscrivener approved these changes

2024-06-03 15:13 UTC, merged