Add Get Into Teaching to the Mission Patches page
DFE-Digital/bat-design-history pull request #499
Opened 2021-11-30 09:01 UTC by MylesJarvis

Context:

This PR aims to add the Get Into Teaching Mascot to the Design History for various reasons:
1 - our new mission approach
2 - to commemorate Ian Jukes leaving GIT. The mascot was designed after him (amongst others in the team).

2021-11-30 11:33 UTC, simonwhatley requested changes

2021-11-30 11:33 UTC, simonwhatley commented on app/mission-patches.md
> +    caption: "This patch celebrated the service entering Public Beta with a mole to represent our emergence. April 2021.
```suggestion
{{ appGallery({
  items: [{
    text: "Get Into Teaching Public Beta",
    caption: "This patch celebrated the service entering Public Beta with a mole to represent our emergence. April 2021."
    }]
}) }}
```

2021-11-30 12:08 UTC, MylesJarvis commented
I need to add a better quality image, will amend PR

2021-12-01 08:35 UTC, adamsilver approved these changes

2021-12-01 08:53 UTC, merged