First continuous application post for Apply
DFE-Digital/bat-design-history pull request #931
Opened 2023-06-01 16:12 UTC by MaeveRoseveare

First post about our initial testing for continuous applications.

2023-06-05 11:10 UTC, frankieroberto requested changes
Love it! Left some minor nitpicks.

Should we add anything around the language of 'inactive', or did we not have any strong findings or that in the end?

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +Candidates have also told us that when they receive a rejection on one course choice, they expect to be able to apply for another course immediately, instead of wait for an outcome on all their cours
```suggestion
Candidates have also told us that when they receive a rejection on one course choice, they expect to be able to apply for another course immediately, instead of waiting for an outcome on all their course choices.
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +* candidates will add another course quicker if an application is unsuccessful
```suggestion
* candidates will apply to another course sooner when an application is unsuccessful
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +We also added some guidance explaining the application process. We do not explain this to candidates anywhere, including on the Get Into Teaching website.
```suggestion
We also added some guidance explaining the application process. We currently do not explain this in detail to candidates anywhere, including on the Get Into Teaching website.
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> + Once a candidate submits an application, the training provider has 40 working days to respond. If they do not, the application is rejected automatically.
```suggestion
 Currently, once a candidate submits an application, the training provider has 40 working days to respond. If they do not, the application is rejected automatically.  
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +* found the guidance on the application process useful so we’re looking to publish this soon
Drop this as it's covered in the section below?

```suggestion
* found the guidance on the application process useful
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +* did not expect applications to be open all year and expected a deadline and all applications to be assessed equally
Might be more readable as 2 bullets?

```suggestion
* did not expect applications to be open all year
* expected a deadline with all applications submitted before the deadline assessed equally
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +* would expect to have an outcome on all their applications before deciding on which to accept
```suggestion
* would expect to have an outcome on all their applications before deciding which to accept
```

2023-06-05 11:10 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +We’ll also be continuing to improve the designs to give candidates more flexibility when applying. We plan to launch some of the designs we tested this recruitment cycle (like publishing guidance on
Split into a separate section?

```suggestion
## Next steps

We’ll continue to iterate the designs.

We plan to launch some of the designs we tested this recruitment cycle, like publishing guidance on the application process.

We’ll launch the bigger changes next recruitment cycle, like allowing applications to become ‘inactive’.
```

2023-06-05 14:25 UTC, MaeveRoseveare commented
> Love it! Left some minor nitpicks.
> 
> Should we add anything around the language of 'inactive', or did we not have any strong findings or that in the end?

Thanks! All good comments. I've added an extra bullet about this and under Next steps to say we need to iterate the design and language around this.

2023-06-07 09:58 UTC, frankieroberto approved these changes

2023-06-07 09:58 UTC, frankieroberto commented on app/posts/apply-for-teacher-training/2023-06-01-changing-application-process.md
> +* understood the term ‘inactive’ and ‘awaiting decision’ but felt they were both ways to cover up that the training provider will not be giving feedback
```suggestion
* understood the terms ‘inactive’ and ‘awaiting decision’ but felt they were both ways to cover up that the training provider will not be giving feedback
```

2023-06-07 10:39 UTC, merged