Moving the equality and diversity survey
DFE-Digital/bat-design-history pull request #957
Opened 2023-06-19 08:59 UTC by MaeveRoseveare

2023-06-21 14:08 UTC, simonwhatley requested changes

2023-06-21 14:08 UTC, simonwhatley commented on app/posts/apply-for-teacher-training/2023-06-19-moving-equality-diversity-survey.md
> +  src: /apply-for-teacher-training/moving-equality-diversity-survey/equality-survey-cover-image.png
```suggestion
  src: equality-survey-cover-image.png
```
You no longer need the file path for the OpenGraph image, as the template handles it for you.

2023-06-22 07:15 UTC, Kateharries commented on app/posts/apply-for-teacher-training/2023-06-19-moving-equality-diversity-survey.md
> +As part of the work to [change the application process](/apply-for-teacher-training/changing-application-process/). We moved the questions about equality and diversity to a new tab called ‘Your detai
You need a comma after the link instead of a full stop.

2023-06-22 07:15 UTC, Kateharries commented on app/posts/apply-for-teacher-training/2023-06-19-moving-equality-diversity-survey.md
> +Candidates only have to fill in these question once because they only submit one application.
Candidates only have to complete these questions once...

2023-06-22 07:15 UTC, Kateharries commented on app/posts/apply-for-teacher-training/2023-06-19-moving-equality-diversity-survey.md
> +As we change the application process, candidates will be able to submit multiple applications and we do not want candidates to have to fill out these questions again and again.
'changed' not 'change'

2023-06-22 11:51 UTC, simonwhatley approved these changes

2023-06-22 14:35 UTC, merged